kind: Service 
apiVersion: v1 
metadata: 
  name: django-service 
spec: 
  selector: 
    app: fundme 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 31000 
  type: NodePort 