# Generated by Django 2.1 on 2019-05-04 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Project Title', max_length=50, unique=True)),
                ('details', models.TextField(max_length=300, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('total_target', models.BigIntegerField(default=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField(max_length=250, null=True)),
                ('comment_reports', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_picture', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_body', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_tag', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='user', max_length=20, null=True)),
                ('lastname', models.CharField(default='user', max_length=20, null=True)),
                ('phone', models.BigIntegerField(default='01000000000', null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/avatar.png', null=True, upload_to='profile_pics/')),
                ('birthday', models.DateField(default=django.utils.timezone.now, null=True)),
                ('portfolio_site', models.URLField(blank=True, default='http://www.facebook.com', null=True)),
                ('country', models.CharField(default='Egypt', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userProfile.Project')),
            ],
            bases=('userProfile.project',),
        ),
        migrations.AddField(
            model_name='projecttags',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectreports',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectreports',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectratings',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectpics',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectdonations',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectdonations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='projectcomments',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
        migrations.AddField(
            model_name='projectcomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Categories'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
        migrations.AddField(
            model_name='featuredproject',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userProfile.Project'),
        ),
    ]
